/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/workspace/dhuodocsfinal/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-5486c160",
    path: "/en/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5486c160").then(next)
    },
  },
  {
    path: "/en/index.html",
    redirect: "/en/"
  },
  {
    name: "v-a92236a2",
    path: "/en/links/ambientesdhuo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a92236a2").then(next)
    },
  },
  {
    name: "v-a0b2bf1a",
    path: "/en/manual/adb2c.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a0b2bf1a").then(next)
    },
  },
  {
    name: "v-11ad270a",
    path: "/en/manual/adb2cazure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11ad270a").then(next)
    },
  },
  {
    name: "v-03065168",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03065168").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-385943da",
    path: "/links/ambientesdhuo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-385943da").then(next)
    },
  },
  {
    name: "v-7b411b74",
    path: "/links/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b411b74").then(next)
    },
  },
  {
    path: "/links/index.html",
    redirect: "/links/"
  },
  {
    name: "v-c7888d50",
    path: "/en/links/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c7888d50").then(next)
    },
  },
  {
    path: "/en/links/index.html",
    redirect: "/en/links/"
  },
  {
    name: "v-7179104e",
    path: "/en/manual/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7179104e").then(next)
    },
  },
  {
    path: "/en/manual/index.html",
    redirect: "/en/manual/"
  },
  {
    name: "v-171a5bf8",
    path: "/manual/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-171a5bf8").then(next)
    },
  },
  {
    path: "/manual/index.html",
    redirect: "/manual/"
  },
  {
    name: "v-3d806fb1",
    path: "/manual/adb2c.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d806fb1").then(next)
    },
  },
  {
    name: "v-04afd253",
    path: "/links/sobrevuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04afd253").then(next)
    },
  },
  {
    name: "v-2ab21fd3",
    path: "/manual/adb2cazure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ab21fd3").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]