/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "DhuoDocs",
  "description": "description",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#8E3CCB"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "Config",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/config/",
      "relativePath": "config/README.md",
      "key": "v-0d746c4b",
      "path": "/config/",
      "headers": [
        {
          "level": 2,
          "title": "foo",
          "slug": "foo"
        },
        {
          "level": 2,
          "title": "bar",
          "slug": "bar"
        }
      ],
      "lastUpdated": "10/21/2021, 9:46:43 PM"
    },
    {
      "title": "DhuoDocs",
      "frontmatter": {
        "home": true,
        "heroImage": "https://storage.googleapis.com/strapi_prd/hero_75b7d7fb43/hero_75b7d7fb43.png",
        "title": "DhuoDocs",
        "tagline": "Documentação para Dhuo",
        "actionText": "Começar →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Tudo em um local só",
            "details": "Minimal setup with markdown-centered project structure helps you focus on writing."
          },
          {
            "title": "Segurança para sua API",
            "details": "Enjoy the dev experience of Vue + webpack, use Vue components in markdown, and develop custom themes with Vue."
          },
          {
            "title": "Features únicas",
            "details": "VuePress generates pre-rendered static HTML for each page, and runs as an SPA once a page is loaded."
          }
        ],
        "footer": "Made by  with ❤️ Eng"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-66b5daec",
      "path": "/",
      "lastUpdated": "10/21/2021, 11:46:21 PM"
    },
    {
      "title": "Instalação On Premise",
      "frontmatter": {},
      "regularPath": "/manual/",
      "relativePath": "manual/README.md",
      "key": "v-542a63cb",
      "path": "/manual/",
      "headers": [
        {
          "level": 2,
          "title": "Introdução",
          "slug": "introducao"
        },
        {
          "level": 2,
          "title": "Módulos e versões",
          "slug": "modulos-e-versoes"
        },
        {
          "level": 2,
          "title": "Repositórios e acessos",
          "slug": "repositorios-e-acessos"
        },
        {
          "level": 2,
          "title": "Pré-requisitos",
          "slug": "pre-requisitos"
        },
        {
          "level": 3,
          "title": "Infraestrutura",
          "slug": "infraestrutura"
        },
        {
          "level": 3,
          "title": "Ferramentas",
          "slug": "ferramentas"
        },
        {
          "level": 3,
          "title": "Endereços de domínio",
          "slug": "enderecos-de-dominio"
        },
        {
          "level": 3,
          "title": "Google storage buckets",
          "slug": "google-storage-buckets"
        },
        {
          "level": 3,
          "title": "Google reCAPTCHA",
          "slug": "google-recaptcha"
        },
        {
          "level": 2,
          "title": "Azure AD B2C",
          "slug": "azure-ad-b2c"
        },
        {
          "level": 2,
          "title": "Instalação dhuo",
          "slug": "instalacao-dhuo"
        },
        {
          "level": 3,
          "title": "Back-ends",
          "slug": "back-ends"
        },
        {
          "level": 3,
          "title": "Front-ends",
          "slug": "front-ends"
        },
        {
          "level": 3,
          "title": "CMS (dhuo-strapi)",
          "slug": "cms-dhuo-strapi"
        },
        {
          "level": 3,
          "title": "Kong (back-end gateway)",
          "slug": "kong-back-end-gateway"
        },
        {
          "level": 3,
          "title": "Setup strapi",
          "slug": "setup-strapi"
        },
        {
          "level": 3,
          "title": "Setup mongodb",
          "slug": "setup-mongodb"
        }
      ]
    },
    {
      "title": "Using Vue in Markdown",
      "frontmatter": {},
      "regularPath": "/manual/using-vue.html",
      "relativePath": "manual/using-vue.md",
      "key": "v-0334d4b8",
      "path": "/manual/using-vue.html",
      "headers": [
        {
          "level": 2,
          "title": "Browser API Access Restrictions",
          "slug": "browser-api-access-restrictions"
        },
        {
          "level": 2,
          "title": "Parte 2",
          "slug": "parte-2"
        }
      ]
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/mystrader/dhuodocsfinal.git",
    "editLinks": false,
    "docsDir": "docs",
    "editLinkText": "Editar página",
    "lastUpdated": true,
    "nav": [
      {
        "text": "Manuais",
        "link": "/manual/"
      },
      {
        "text": "Produtos",
        "link": "/produtos/"
      },
      {
        "text": "Engineering",
        "link": "https://www.engdb.com.br/"
      }
    ],
    "sidebar": {
      "/manual/": [
        {
          "title": "Manuais",
          "collapsable": true,
          "children": [
            "",
            "using-vue"
          ]
        }
      ]
    }
  }
}